const TeamsActionTypes = {
  FETCH_TEAMS_START: 'FETCH_TEAMS_START',
  FETCH_TEAMS_SUCCESS: 'FETCH_TEAMS_SUCCESS',
  FETCH_TEAMS_FAILURE: 'FETCH_TEAMS_FAILURE',
  ADD_PLAYERS_INFO: 'ADD_PLAYERS_INFO'
}
export default TeamsActionTypes;